### ISSUE TITLE
Refactoring of the instance permutation mechanism

### ISSUE THREAD

**Issue by gasse** [ds4dm/ecole#163] opened 2021-04-21 16:22 UTC
## Describe the problem or improvement suggested
There is currently no way to permute an instance loaded from an instance file
```python
env.reset("instance.lp")
```
Also, it is not clear in the documentation what is the expected behavior: is there instance permutation happening ? Is the environment responsible for it ? Right now `env.reset()` sets the following SCIP parameters with no effect:
```
randomization/permutevars
randomization/permutationseed
```

## Describe the solution you would like

Environments should not be responsible for instance permutation (constraints / variables), it should be the responsibility of the user.

By default `env.reset("instance.lp")` should not do any permutation

An instance permutation option should be offered by the `Model.from_file()` method:
```python
Model.from_file("instance.lp", scip_params={
    "randomization/permutevars": True,
    "randomization/permutationseed": 3})
```

An instance permutation option should be offered by the `env.reset()`method, either with
```python
env.reset("instance.lp", scip_loading_params={
    "randomization/permutevars": True,
    "randomization/permutationseed": 3})
```
or
```python
env.reset("instance.lp", permutevars=True, permutationseed=3)
```

An instance permutation option should be offered by instance generators

These two codes should be equivalent:
```python
env.reset("instance.lp", scip_loading_params={
    "randomization/permutevars": True,
    "randomization/permutationseed": 3})
```
```python
model = ecole.scip.Model.from_file("instance.lp", scip_params={
    "randomization/permutevars": True,
    "randomization/permutationseed": 3})
env.reset(model)
```

## Describe alternatives you have considered
We could require users to use an instance generator if they want permutations. We could also fornid the use case where users pass a string to `env.reset()` altogether, so that they must explicitly pass an `ecole.scip.Model` object, where permutation already happened.

## Additional context
See discussions in issue #159

**Comment by gasse** [comment] 2021-04-22 17:43
About SCIP parameters in general, I think it is ok if users provide an instance (SCIP model) with non-default SCIP parameters to `env.reset(instance)`. SCIP environments can override some parameters (e.g., the SCIP seed for randomization during solving, or environment-specific parameters), but they should not rely on the fact that the provided model has default parameters. As such, users can change SCIP parameters before feeding an instance to an environment, and instance generators can change SCIP parameters of the instances as well.

**Comment by dchetelat** [comment] 2021-04-23 13:42
So then there would be three sources of SCIP parameters?

1. In the environment constructor
2. In an instance generator
3. In the reset function

?

**Comment by gasse** [comment] 2021-04-23 14:05
Only two I think no ? At construction, environments do not handle a SCIP model yet ?

**Comment by dchetelat** [comment] 2021-04-23 14:08
Ok so you want to remove the current `scip_parameters` argument in the environment constructor?

**Comment by gasse** [comment] 2021-04-23 14:23
Oh I see what you mean, yes we provide SCIP parameters there, but they will be set during `env.reset()`.

> Ok so you want to remove the current `scip_parameters` argument in the environment constructor?
No I wouldn't do that.

I agree it is a bit confusing to have the option to set SCIP parameters everywhere. Ok so what about not having SCIP parameters as an argument in `env.reset()` ? Say we adopt the following:
 - in the constructor, environments accept only SCIP parameters which have an effect during solving. If users pass SCIP parameters `randomization/permutevars` or `randomization/permutationseed`, we issue a warning that those will have no effect.
 - in `env.reset()` we remove the option to pass SCIP parameters, and hence to permute instances.
 - to obtain instance permutation, users either must use an instance generator, or an `ecole.scip.Model` ?

If we do that, then there are only two places where we can set SCIP parameters: when creating an environment, and when creating a SCIP Model.

**Comment by dchetelat** [comment] 2021-04-23 14:48
> in the constructor, environments accept only SCIP parameters which have an effect during solving. If users pass SCIP parameters randomization/permutevars or randomization/permutationseed, we issue a warning that those will have no effect.

Ok but there's a million parameters, how will you know which will have no effect?

---

I have a crazy idea. How about having _no_ scip parameters in instance generators (!), or in reset: only in the environment constructor like right now. 

But that when you pass an instance to `reset`, the instance is saved to a temporary file (`SCIPwriteProb`), a model is created, environment scip parameters applied and the problem is reloaded (`SCIPreadProb`)? Then scip parameters will always apply! And you would even have the crazy cool thing that `randomization/permutevars` can be applied even to instances that have been created using an instance generator!

The only downside is that it is slow (writing to disk and reading again).

**Comment by gasse** [comment] 2021-04-23 15:10
1) that sounds crazy :P
2) what if a user provides an exotic `Model`, say, with lazy constraints and a constraint handler ? No sure you can save that to a file and re-load.

How nice it would be if SCIP's permutation was not done while the instance is loaded but afterwards, with a single method to call... Maybe we could suggest SCIP developers to offer that feature in future releases ?

**Comment by AntoinePrv** [comment] 2021-04-23 16:06
Perhaps we could not have SCIP parameters in `env.reset`, but, when you pass a string, then constructor parameters would be set *before* loading the model?

The downside is that it create a discrepancy between string and `Model`s, but unless you ignore loading parameters in the environment, that will always be the case.

**Comment by AntoinePrv** [comment] 2021-04-23 16:08
What if we permute the problems ourselves [`SCIPpermuteProb`](https://www.scipopt.org/doc-7.0.2/html/group__GlobalProblemMethods.php#gadd4d1e87c0e2fc33f330438d0789e980) in `set_dynamics_random_state` ?

 - [x] Works for string and `Model`s without specific treatment
 - [x] Is overridable

**Comment by dchetelat** [comment] 2021-04-23 16:30
> Perhaps we could not have SCIP parameters in env.reset, but, when you pass a string, then constructor parameters would be set before loading the model?

Yes that was my proposal during the Ecole meeting. It's not ideal of course as, like you mention, it will have the counter-intuitive effect that some parameters (like randomization) will not be applied to instances from instance generators.

> What if we permute the problems ourselves (SCIPpermuteProb) in set_dynamics_random_state ?

Although I do care about permutation, I wanted to have a more general discussion about SCIP parameters in general... Maybe there's other parameters that need to be set before the `SCIPreadProb`, for example.

**Comment by dchetelat** [comment] 2021-04-23 16:42
>   1. that sounds crazy :P
>   2. what if a user provides an exotic Model, say, with lazy constraints and a constraint handler ? No sure you can save that to a file and re-load.

Yeah good point.

Ok, I thought about it more and here's a thought. Right now we already do a copy of the instance when we load an instance,
https://github.com/ds4dm/ecole/blob/2201252db3427786b437174e2a0541aa47e29bc7/python/src/ecole/environment.py#L103-L107
which copies the scip object,
https://github.com/ds4dm/ecole/blob/2201252db3427786b437174e2a0541aa47e29bc7/libecole/src/scip/model.cpp#L40-L42
and ultimately
https://github.com/ds4dm/ecole/blob/2201252db3427786b437174e2a0541aa47e29bc7/libecole/src/scip/scimpl.cpp#L53-L66

Perhaps if we set the SCIP parameters somewhere at the right place, the new SCIP would get their effect, e.g. the columns and rows would get permuted correctly? Just a theory, maybe SCIP doesn't work like that.

But in general I like the idea that we would be able to get, say, row/variable permutation (or other pre-loading effects) on instances that have been previously created by instance generators. That would be intuitive.

**Comment by AntoinePrv** [comment] 2021-06-12 17:56
@dchetelat @gasse with SCIP 7.0.3 I think we can close this, right?

**Comment by gasse** [comment] 2021-06-15 04:13
I think so yes. Maybe @dchetelat you can confirm ?

**Comment by dchetelat** [comment] 2021-06-18 18:29
Yes, this and #159 .

**Closed by dchetelat** 2021-06-18 18:29 UTC
Labels: type/enhancement 🚀
